version: 2.0

stylesheets:
  - { path: "package://multi_data_monitor/css/plugins/simple.css", target: Simple }
  - { path: "package://multi_data_monitor/css/plugins/titled.css", target: Titled }
  - { path: "package://multi_data_monitor/css/colors.css" }


widgets:
  - class: Matrix 
    cols: 1

    items:
      - class: Simple
        value: Sensor Data Covariance

      - class: Matrix
        cols: 5
        items:
          - gnss_pos_cov

      - class: Simple
        value: EKF Input Covariance

      - class: Matrix
        cols: 5
        items:
          - imu_gnss_poser_pos_cov
          - imu_gnss_poser_orie_cov
          - gyro_odom_linear_vel_x_cov
          - gyro_odom_ang_vel_cov

      - class: Simple
        value: EKF Output Covariance

      - class: Matrix
        cols: 6
        items:
          - ekf_output_x
          - ekf_output_y
          - ekf_output_z
          - ekf_output_ori_x
          - ekf_output_ori_y
          - ekf_output_ori_z

      - class: Simple
        value: Actuation Cmd (Kart)

      - class: Matrix
        cols: 3
        items:
          - throttle
          - brake 
          - steering 

  # Condition https://github.com/tier4/multi_data_monitor/blob/main/multi_data_monitor/documents/classes/others/conditions.md
  # Sesor Data
  # Measured
  - class: Titled
    label: gnss_pos_cov
    title: GNSS Pos Cov  
    input: { class: subscription, topic: /sensing/gnss/pose_with_covariance, field: pose.covariance@0}
    rules:
      - { class: Precision, digits: 0 }
      - class: SetFirstIf
        type: real
        list:
          - { ge: 200.0, attrs: { back-color: red } }
          - { ge: -1000.0, attrs: { back-color: white } }

  # EKF Input Cov
  - class: Titled
    label: imu_gnss_poser_pos_cov
    title: GNSS Pos Cov
    input: { class: subscription, topic: /localization/imu_gnss_poser/pose_with_covariance, field: pose.covariance@0}
    rules:
      - { class: Precision, digits: 2 }
      - class: SetFirstIf
        type: real
        list:
          - { ge: -1000.0, attrs: { back-color: white } }

  - class: Titled
    label: imu_gnss_poser_orie_cov
    title: GNSS Orie Cov
    input: { class: subscription, topic: /localization/imu_gnss_poser/pose_with_covariance, field: pose.covariance@21}
    rules:
      - { class: Precision, digits: 2 }
      - class: SetFirstIf
        type: real
        list:
          - { ge: -1000.0, attrs: { back-color: white } }

  - class: Titled
    label: gyro_odom_linear_vel_x_cov
    title: GyroOdom LinVel X
    input: { class: subscription, topic: /localization/twist_estimator/twist_with_covariance, field: twist.covariance@0}
    rules:
      - { class: Precision, digits: 2 }
      - class: SetFirstIf
        type: real
        list:
          - { ge: -1000.0, attrs: { back-color: white } }
 
  - class: Titled
    label: gyro_odom_ang_vel_cov
    title: GyroOdom AngVel
    input: { class: subscription, topic: /localization/twist_estimator/twist_with_covariance, field: twist.covariance@21}
    rules:
      - { class: Precision, digits: 4 }
      - class: SetFirstIf
        type: real
        list:
          - { ge: -1000.0, attrs: { back-color: white } }
  # EKF Output Cov
  - class: Titled
    label: ekf_output_x
    title: X
    input: { class: subscription, topic: /localization/kinematic_state, field: pose.covariance@0}
    rules:
      - { class: Precision, digits: 2 }
      - class: SetFirstIf
        type: real
        list:
          - { ge: -1000.0, attrs: { back-color: white } }

  - class: Titled
    label: ekf_output_y
    title: Y
    input: { class: subscription, topic: /localization/kinematic_state, field: pose.covariance@7}
    rules:
      - { class: Precision, digits: 2 }
      - class: SetFirstIf
        type: real
        list:
          - { ge: -1000.0, attrs: { back-color: white } }

  - class: Titled
    label: ekf_output_z
    title: Z
    input: { class: subscription, topic: /localization/kinematic_state, field: pose.covariance@14}
    rules:
      - { class: Precision, digits: 2 }
      - class: SetFirstIf
        type: real
        list:
          - { ge: -1000.0, attrs: { back-color: white } }

  - class: Titled
    label: ekf_output_ori_x
    title: Ori_X
    input: { class: subscription, topic: /localization/kinematic_state, field: pose.covariance@21}
    rules:
      - { class: Precision, digits: 2 }
      - class: SetFirstIf
        type: real
        list:
          - { ge: -1000.0, attrs: { back-color: white } }
  - class: Titled
    label: ekf_output_ori_y
    title: Ori_Y
    input: { class: subscription, topic: /localization/kinematic_state, field: pose.covariance@28}
    rules:
      - { class: Precision, digits: 2 }
      - class: SetFirstIf
        type: real
        list:
          - { ge: -1000.0, attrs: { back-color: white } }
  - class: Titled
    label: ekf_output_ori_z
    title: Ori_Z
    input: { class: subscription, topic: /localization/kinematic_state, field: pose.covariance@35}
    rules:
      - { class: Precision, digits: 2 }
      - class: SetFirstIf
        type: real
        list:
          - { ge: -1000.0, attrs: { back-color: white } }
  # Actuation_CMD(Pedal)
  - class: Titled
    label: throttle 
    title: Accel Pedal
    input: { class: subscription, topic: /control/command/actuation_cmd, field: actuation.accel_cmd}
    rules:
      - { class: Precision, digits: 2 }
      - class: SetFirstIf
        type: real
        list:
          - { ge: 0.95, attrs: { back-color: cyan } }
          - { lt: 0.95, attrs: { back-color: white } }

  - class: Titled
    label: brake 
    title: Brake Pedal 
    input: { class: subscription, topic: /control/command/actuation_cmd, field: actuation.brake_cmd}
    rules:
      - { class: Precision, digits: 2 }
      - class: SetFirstIf
        type: real
        list:
          - { ge: 0.5, attrs: { back-color: yellow } }
          - { eq: 0.0, attrs: { back-color: cyan } }
          - { lt: 0.5, attrs: { back-color: white } }

  - class: Titled
    label: steering 
    title: Steering Cmd[rad]
    input: { class: subscription, topic: /control/command/actuation_cmd, field: actuation.steer_cmd}
    rules:
      - { class: Precision, digits: 2 }
      - class: SetFirstIf
        type: real
        list:
          - { ge: -1000.0, attrs: { back-color: white } }





# Conversion https://github.com/tier4/multi_data_monitor/blob/main/multi_data_monitor/documents/classes/filter/units.md
streams:
  - { label: control_cmd_mps, class: subscription, topic: /control/command/control_cmd, field: longitudinal.speed }
  - { label: control_cmd_kph, class: apply, input: control_cmd_mps, rules: f1 }
  # Measured
    # Velocity
  - { label: measured_longitudinal_vel_mps, class: subscription, topic: /vehicle/status/velocity_status, field: longitudinal_velocity }
  - { label: measured_lateral_vel_mps, class: subscription, topic: /vehicle/status/velocity_status, field: lateral_velocity }
  - { label: measured_longitudinal_vel_kph, class: apply, input: measured_longitudinal_vel_mps, rules: f1 }
  - { label: measured_lateral_vel_kph, class: apply, input: measured_lateral_vel_mps, rules: f1 }




filters:
  - { class: Units, label: f1, mode: mps_to_kph }
  - { class: Units, label: f2, mode: rad_to_deg }
