version: 2.0

stylesheets:
  - { path: "package://multi_data_monitor/css/plugins/simple.css", target: Simple }
  - { path: "package://multi_data_monitor/css/plugins/titled.css", target: Titled }
  - { path: "package://multi_data_monitor/css/colors.css" }


widgets:
  - class: Matrix 
    cols: 1

    items:
      - class: Simple
        value: Sensor Data Covariance

      - class: Matrix
        cols: 5
        items:
          - gnss_pos_cov
          - imu_data_angvel_cov
          - odom_lin_cov_x
          - odom_ang_cov_z

      - class: Simple
        value: EKF Input Covariance

      - class: Matrix
        cols: 5
        items:
          - imu_gnss_poser_pos_cov
          - imu_gnss_poser_orie_cov
          - gyro_odom_linear_vel_x_cov
          - gyro_odom_ang_vel_cov

      - class: Simple
        value: EKF Output Covariance

      - class: Matrix
        cols: 6
        items:
          - ekf_output_x
          - ekf_output_y
          - ekf_output_z
          - ekf_output_ori_x
          - ekf_output_ori_y
          - ekf_output_ori_z

      - class: Simple
        value: Measured

      - class: Matrix
        cols: 6
        items:
          - measured_steering_deg
          - measured_longitudinal_vel_kph
          - measured_heading_rate_deg

          - measured_steering_rad
          - measured_longitudinal_vel_mps
          - measured_heading_rate_rad

          # - measured_lateral_vel_mps
          # - measured_lateral_vel_kph
          - measured_acceleration
          - measured_steering_velocity


      - class: Simple
        value: Actuation Cmd (Kart)

      - class: Matrix
        cols: 3
        items:
          - throttle
          - brake 
          - steering 

      - class: Simple 
        const: Control Cmd

      - class: Matrix
        cols: 3
        items:
          - speed_kph
          - acceleration
          - control_steering_tire_angle_rad
          - speed_mps
          - control_steering_tire_angle_deg



  # Condition https://github.com/tier4/multi_data_monitor/blob/main/multi_data_monitor/documents/classes/others/conditions.md
  # Sesor Data
  # Measured
  - class: Titled
    label: gnss_pos_cov
    title: GNSS Pos Cov  
    input: { class: subscription, topic: /sensing/gnss/pose_with_covariance, field: pose.covariance@0}
    rules:
      - { class: Precision, digits: 0 }
      - class: SetFirstIf
        type: real
        list:
          - { ge: 200.0, attrs: { back-color: red } }
          - { ge: -1000.0, attrs: { back-color: white } }

  - class: Titled
    label: imu_data_angvel_cov
    title: IMU AngVel Cov
    input: { class: subscription, topic: /sensing/imu/imu_data, field: angular_velocity_covariance@0}
    rules:
      - { class: Precision, digits: 4 }
      - class: SetFirstIf
        type: real
        list:
          - { ge: -1000.0, attrs: { back-color: white } }

  - class: Titled
    label: odom_lin_cov_x
    title: Odom Lin X Cov
    input: { class: subscription, topic: /sensing/vehicle_velocity_converter/twist_with_covariance, field: twist.covariance@0}
    rules:
      - { class: Precision, digits: 2 }
      - class: SetFirstIf
        type: real
        list:
          - { ge: -1000.0, attrs: { back-color: white } }
  
  - class: Titled
    label: odom_ang_cov_z
    title: Odom Ang Z Cov
    input: { class: subscription, topic: /sensing/vehicle_velocity_converter/twist_with_covariance, field: twist.covariance@35}
    rules:
      - { class: Precision, digits: 2 }
      - class: SetFirstIf
        type: real
        list:
          - { ge: -1000.0, attrs: { back-color: white } }

  # EKF Input Cov
  - class: Titled
    label: imu_gnss_poser_pos_cov
    title: GNSS Pos Cov
    input: { class: subscription, topic: /localization/imu_gnss_poser/pose_with_covariance, field: pose.covariance@0}
    rules:
      - { class: Precision, digits: 2 }
      - class: SetFirstIf
        type: real
        list:
          - { ge: -1000.0, attrs: { back-color: white } }

  - class: Titled
    label: imu_gnss_poser_orie_cov
    title: GNSS Orie Cov
    input: { class: subscription, topic: /localization/imu_gnss_poser/pose_with_covariance, field: pose.covariance@21}
    rules:
      - { class: Precision, digits: 2 }
      - class: SetFirstIf
        type: real
        list:
          - { ge: -1000.0, attrs: { back-color: white } }

  - class: Titled
    label: gyro_odom_linear_vel_x_cov
    title: GyroOdom LinVel X
    input: { class: subscription, topic: /localization/twist_estimator/twist_with_covariance, field: twist.covariance@0}
    rules:
      - { class: Precision, digits: 2 }
      - class: SetFirstIf
        type: real
        list:
          - { ge: -1000.0, attrs: { back-color: white } }
 
  - class: Titled
    label: gyro_odom_ang_vel_cov
    title: GyroOdom AngVel
    input: { class: subscription, topic: /localization/twist_estimator/twist_with_covariance, field: twist.covariance@21}
    rules:
      - { class: Precision, digits: 4 }
      - class: SetFirstIf
        type: real
        list:
          - { ge: -1000.0, attrs: { back-color: white } }
  # EKF Output Cov
  - class: Titled
    label: ekf_output_x
    title: X
    input: { class: subscription, topic: /localization/kinematic_state, field: pose.covariance@0}
    rules:
      - { class: Precision, digits: 2 }
      - class: SetFirstIf
        type: real
        list:
          - { ge: -1000.0, attrs: { back-color: white } }

  - class: Titled
    label: ekf_output_y
    title: Y
    input: { class: subscription, topic: /localization/kinematic_state, field: pose.covariance@7}
    rules:
      - { class: Precision, digits: 2 }
      - class: SetFirstIf
        type: real
        list:
          - { ge: -1000.0, attrs: { back-color: white } }

  - class: Titled
    label: ekf_output_z
    title: Z
    input: { class: subscription, topic: /localization/kinematic_state, field: pose.covariance@14}
    rules:
      - { class: Precision, digits: 2 }
      - class: SetFirstIf
        type: real
        list:
          - { ge: -1000.0, attrs: { back-color: white } }

  - class: Titled
    label: ekf_output_ori_x
    title: Ori_X
    input: { class: subscription, topic: /localization/kinematic_state, field: pose.covariance@21}
    rules:
      - { class: Precision, digits: 2 }
      - class: SetFirstIf
        type: real
        list:
          - { ge: -1000.0, attrs: { back-color: white } }
  - class: Titled
    label: ekf_output_ori_y
    title: Ori_Y
    input: { class: subscription, topic: /localization/kinematic_state, field: pose.covariance@28}
    rules:
      - { class: Precision, digits: 2 }
      - class: SetFirstIf
        type: real
        list:
          - { ge: -1000.0, attrs: { back-color: white } }
  - class: Titled
    label: ekf_output_ori_z
    title: Ori_Z
    input: { class: subscription, topic: /localization/kinematic_state, field: pose.covariance@35}
    rules:
      - { class: Precision, digits: 2 }
      - class: SetFirstIf
        type: real
        list:
          - { ge: -1000.0, attrs: { back-color: white } }
  # Measured
  - class: Titled
    label: measured_steering_rad
    title: Steering[rad]  
    input: { class: subscription, topic: /vehicle/status/steering_status, field: steering_tire_angle}
    rules:
      - { class: Precision, digits: 2 }
      - class: SetFirstIf
        type: real
        list:
          - { ge: -1000.0, attrs: { back-color: white } }

  - class: Titled
    label: measured_longitudinal_vel_mps
    title: Long Vel[m/s]
    input: measured_longitudinal_vel_mps 
    rules:
      - { class: Precision, digits: 1 }
      - class: SetFirstIf
        type: real
        list:
          - { ge: -1000.0, attrs: { back-color: white } }



  - class: Titled
    label: measured_longitudinal_vel_kph
    title: Long Vel[km/h]
    input: measured_longitudinal_vel_kph
    rules:
      - { class: Precision, digits: 1 }
      - class: SetFirstIf
        type: real
        list:
          - { ge: -1000.0, attrs: { back-color: white } }


  - class: Titled
    label: measured_heading_rate_rad
    title: Heading Rate
    input: { class: subscription, topic: /vehicle/status/velocity_status, field: heading_rate}
    rules:
      - { class: Precision, digits: 2 }
      - class: SetFirstIf
        type: real
        list:
          - { ge: -1000.0, attrs: { back-color: white } }

  - class: Titled
    label: measured_steering_deg
    title: Steering[deg]  
    input: measured_steering_deg
    rules:
      - { class: Precision, digits: 1 }
      - class: SetFirstIf
        type: real
        list:
          - { ge: -1000.0, attrs: { back-color: white } }
  
  - class: Titled
    label: measured_heading_rate_deg
    title: Heading Rate[deg/s]?
    input: measured_heading_rate_deg
    rules:
      - { class: Precision, digits: 1 }
      - class: SetFirstIf
        type: real
        list:
          - { ge: -1000.0, attrs: { back-color: white } }

  - class: Titled
    label: measured_acceleration
    title: Acceleration[m/ss]
    input: { class: subscription, topic: /vehicle/status/acceleration, field: data}
    rules:
      - { class: Precision, digits: 1 }
      - class: SetFirstIf
        type: real
        list:
          - { ge: -1000.0, attrs: { back-color: white } }

  - class: Titled
    label: measured_steering_velocity
    title: SteerVel[deg/s]
    input: { class: subscription, topic: /vehicle/status/angular_velocity, field: data}
    rules:
      - { class: Precision, digits: 1 }
      - class: SetFirstIf
        type: real
        list:
          - { ge: -1000.0, attrs: { back-color: white } }

  # Actuation_CMD(Pedal)
  - class: Titled
    label: throttle 
    title: Accel Pedal
    input: { class: subscription, topic: /control/command/actuation_cmd, field: actuation.accel_cmd}
    rules:
      - { class: Precision, digits: 2 }
      - class: SetFirstIf
        type: real
        list:
          - { ge: 0.95, attrs: { back-color: cyan } }
          - { lt: 0.95, attrs: { back-color: white } }

  - class: Titled
    label: brake 
    title: Brake Pedal 
    input: { class: subscription, topic: /control/command/actuation_cmd, field: actuation.brake_cmd}
    rules:
      - { class: Precision, digits: 2 }
      - class: SetFirstIf
        type: real
        list:
          - { ge: 0.5, attrs: { back-color: yellow } }
          - { eq: 0.0, attrs: { back-color: cyan } }
          - { lt: 0.5, attrs: { back-color: white } }

  - class: Titled
    label: steering 
    title: Steering Cmd[rad]
    input: { class: subscription, topic: /control/command/actuation_cmd, field: actuation.steer_cmd}
    rules:
      - { class: Precision, digits: 2 }
      - class: SetFirstIf
        type: real
        list:
          - { ge: -1000.0, attrs: { back-color: white } }

  - class: Titled
    label: speed_kph
    title: Speed[km/h]
    input: control_cmd_kph 
    rules:
      - { class: Precision, digits: 1 }
      - class: SetFirstIf
        type: real
        list:
          - { ge: -1000.0, attrs: { back-color: white } }

  # Control_CMD
  - class: Titled
    label: speed_mps 
    title: Speed[m/s]  
    input: { class: subscription, topic: /control/command/control_cmd, field: longitudinal.speed}
    rules:
      - { class: Precision, digits: 2 }
      - class: SetFirstIf
        type: real
        list:
          - { ge: -1000.0, attrs: { back-color: white } }

  - class: Titled
    label: acceleration 
    title: Acceleration[m/ss]
    input: { class: subscription, topic: /control/command/control_cmd, field: longitudinal.acceleration}
    rules:
      - { class: Precision, digits: 2 }
      # - { class: SetIf, type: real, ge: 0.95, attrs: { back-color: cyan }  }
      - class: SetFirstIf
        type: real
        list:
          - { ge: -1000.0, attrs: { back-color: white } }

  - class: Titled
    label: control_steering_tire_angle_rad
    title: Steering Cmd[rad]
    input: control_steering_cmd_rad
    rules:
      - { class: Precision, digits: 2 }
      - class: SetFirstIf
        type: real
        list:
          - { ge: -1000.0, attrs: { back-color: white } }

  - class: Titled
    label: control_steering_tire_angle_deg 
    title: Steering Cmd[deg]  
    input: control_steering_cmd_deg
    rules:
      - { class: Precision, digits: 1 }
      - class: SetFirstIf
        type: real
        list:
          - { ge: -1000.0, attrs: { back-color: white } }



# Conversion https://github.com/tier4/multi_data_monitor/blob/main/multi_data_monitor/documents/classes/filter/units.md
streams:
  - { label: control_cmd_mps, class: subscription, topic: /control/command/control_cmd, field: longitudinal.speed }
  - { label: control_cmd_kph, class: apply, input: control_cmd_mps, rules: f1 }
  # Measured
    # Velocity
  - { label: measured_longitudinal_vel_mps, class: subscription, topic: /vehicle/status/velocity_status, field: longitudinal_velocity }
  - { label: measured_lateral_vel_mps, class: subscription, topic: /vehicle/status/velocity_status, field: lateral_velocity }
  - { label: measured_longitudinal_vel_kph, class: apply, input: measured_longitudinal_vel_mps, rules: f1 }
  - { label: measured_lateral_vel_kph, class: apply, input: measured_lateral_vel_mps, rules: f1 }
    # Steering
  - { label: measured_steering_rad, class: subscription, topic: /vehicle/status/steering_status, field: steering_tire_angle }
  - { label: measured_heading_rate_rad, class: subscription, topic: /vehicle/status/velocity_status, field: heading_rate }
  - { label: measured_steering_deg, class: apply, input: measured_steering_rad, rules: f2 }
  - { label: measured_heading_rate_deg, class: apply, input: measured_heading_rate_rad, rules: f2 }
  # Control_CMD
  - { label: control_steering_cmd_rad, class: subscription, topic: /control/command/control_cmd, field: lateral.steering_tire_angle }
  - { label: control_steering_cmd_deg, class: apply, input: control_steering_cmd_rad, rules: f2 }




filters:
  - { class: Units, label: f1, mode: mps_to_kph }
  - { class: Units, label: f2, mode: rad_to_deg }
