/**:
  ros__parameters:
    ## base: Right Data(vertical)
    angular_velocity_offset_x: -0.01    # [rad/s]
    angular_velocity_offset_y: 0.002     # [rad/s]
    angular_velocity_offset_z: -0.006  # [rad/s]
    # Just setting covariance matrix
    angular_velocity_stddev_xx: 0.0  # [rad/s]
    angular_velocity_stddev_yy: 0.0   # [rad/s]
    angular_velocity_stddev_zz: 0.0   # [rad/s]
    # base_link: imu_link
